import React,{useEffect,useMemo,useState}from'react';import{ActivityIndicator,Alert,FlatList,Pressable,ScrollView,StatusBar,StyleSheet,Switch,Text,TextInput,View}from'react-native';
import{NavigationContainer}from'@react-navigation/native';import{createNativeStackNavigator,NativeStackScreenProps}from'@react-navigation/native-stack';
import{useDrivers,Driver}from'./src/store';
import{QueryClient,QueryClientProvider,useMutation,useQuery,useQueryClient}from'@tanstack/react-query';
function Drivers(){const drivers=useDrivers(v=>v.drivers),add=useDrivers(v=>v.add);const[name,setName]=useState('');return <View style={s.page}><Text style={s.title}>Conductores</Text><View style={s.row}><TextInput style={[s.input,{flex:1}]} value={name} onChangeText={setName} placeholder="Nombre" placeholderTextColor="#8795a1"/><Pressable style={s.button} onPress={()=>{if(name.trim()){add(name.trim());setName('')}}}><Text style={s.btn}>Agregar</Text></Pressable></View><FlatList data={drivers} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.name}</Text><Text style={s.sub}>{item.unit}</Text></View>}/></View>}
type Routes={Inicio:undefined;Conductores:undefined;Viajes:undefined;Ingresos:undefined};const Stack=createNativeStackNavigator<Routes>();type Trip={id:string;origin:string;destination:string;fare:number};let trips:Trip[]=[{id:'t1',origin:'Terminal',destination:'Centro',fare:12000},{id:'t2',origin:'Aeropuerto',destination:'Norte',fare:25000}];const client=new QueryClient({defaultOptions:{queries:{retry:0,refetchOnWindowFocus:false}}});async function getTrips(){await new Promise(r=>setTimeout(r,180));return trips}async function addTrip(t:Omit<Trip,'id'>){await new Promise(r=>setTimeout(r,180));const item={...t,id:String(Date.now())};trips=[item,...trips];return item}
function Home({navigation}:NativeStackScreenProps<Routes,'Inicio'>){const drivers=useDrivers(v=>v.drivers);return <View style={s.page}><Text style={s.title}>Cooperativa de Taxis</Text><Text style={s.sub}>Semana 5 · consultas y mutations con TanStack Query</Text><View style={s.card}><Text style={s.name}>{drivers.length} conductores</Text><Text style={s.sub}>Usa los accesos para consultar datos y crear un servicio.</Text></View><Pressable style={s.button} onPress={()=>navigation.navigate('Conductores')}><Text style={s.btn}>Conductores</Text></Pressable><Pressable style={s.button} onPress={()=>navigation.navigate('Viajes')}><Text style={s.btn}>Viajes</Text></Pressable><Pressable style={s.button} onPress={()=>navigation.navigate('Ingresos')}><Text style={s.btn}>Ingresos</Text></Pressable></View>}
function Drivers(){const drivers=useDrivers(v=>v.drivers);return <FlatList style={s.page} data={drivers} keyExtractor={x=>x.id} ListHeaderComponent={<Text style={s.title}>Conductores</Text>} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.name}</Text><Text style={s.sub}>{item.unit}</Text></View>}/>}
function Trips(){const qc=useQueryClient(),q=useQuery({queryKey:['trips'],queryFn:getTrips}),m=useMutation({mutationFn:addTrip,onSuccess:()=>qc.invalidateQueries({queryKey:['trips']})});return <View style={s.page}><Text style={s.title}>Viajes</Text><Pressable style={s.button} onPress={()=>m.mutate({origin:'Terminal',destination:'Centro',fare:12000})}><Text style={s.btn}>{m.isPending?'Guardando…':'Agregar viaje de ejemplo'}</Text></Pressable>{q.isLoading?<ActivityIndicator color="#61dafb"/>:<FlatList data={q.data??[]} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.origin} → {item.destination}</Text><Text style={s.sub}>Tarifa: {item.fare.toLocaleString('es-CO')} COP</Text></View>}/>}</View>}
function Income(){const q=useQuery({queryKey:['trips'],queryFn:getTrips});const total=(q.data??[]).reduce((sum,t)=>sum+t.fare,0);return <View style={s.page}><Text style={s.title}>Ingresos registrados</Text><Text style={s.amount}>{total.toLocaleString('es-CO')} COP</Text><Text style={s.sub}>Total calculado sobre {q.data?.length??0} viajes.</Text></View>}
function Main(){return <NavigationContainer><Stack.Navigator screenOptions={{headerStyle:{backgroundColor:'#161b22'},headerTintColor:'#fff',contentStyle:{backgroundColor:'#0d1117'}}}><Stack.Screen name="Inicio" component={Home}/><Stack.Screen name="Conductores" component={Drivers}/><Stack.Screen name="Viajes" component={Trips}/><Stack.Screen name="Ingresos" component={Income}/></Stack.Navigator></NavigationContainer>}
export default function App(){return <QueryClientProvider client={client}><Main/></QueryClientProvider>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0d1117',padding:18},title:{color:'#fff',fontSize:25,fontWeight:'900'},sub:{color:'#aeb8c4',marginTop:6,marginBottom:8},input:{backgroundColor:'#161b22',borderColor:'#30363d',borderWidth:1,borderRadius:10,padding:12,color:'#fff',marginVertical:5},row:{flexDirection:'row',alignItems:'center',gap:8},button:{backgroundColor:'#238636',borderRadius:9,padding:12,alignItems:'center',marginVertical:7},btn:{color:'#fff',fontWeight:'800'},card:{backgroundColor:'#161b22',borderColor:'#30363d',borderWidth:1,borderRadius:12,padding:14,marginVertical:7},name:{color:'#fff',fontWeight:'800',fontSize:16},error:{color:'#ff8a80',marginVertical:8},link:{color:'#61dafb',textAlign:'center',fontWeight:'700',padding:12},amount:{color:'#8ce99a',fontSize:27,fontWeight:'900',marginTop:15}});