import React, { useRef, useState } from 'react';
import { Animated, LayoutAnimation, Pressable, SafeAreaView, StyleSheet, Text, UIManager, View, Platform } from 'react-native';

if (Platform.OS === 'android' && UIManager.setLayoutAnimationEnabledExperimental) UIManager.setLayoutAnimationEnabledExperimental(true);
export function AnimationsScreen(): React.JSX.Element {
 const fade=useRef(new Animated.Value(0)).current; const slide=useRef(new Animated.Value(0)).current; const scale=useRef(new Animated.Value(1)).current; const decay=useRef(new Animated.Value(0)).current; const stepOne=useRef(new Animated.Value(0)).current; const stepTwo=useRef(new Animated.Value(0)).current; const stepThree=useRef(new Animated.Value(0)).current; const [items,setItems]=useState(['Servicio urbano','Traslado aeropuerto']);
 const opacity=fade.interpolate({inputRange:[0,1],outputRange:[0.25,1]});
 function entrance():void{fade.setValue(0);slide.setValue(0);Animated.parallel([Animated.timing(fade,{toValue:1,duration:650,useNativeDriver:true}),Animated.spring(slide,{toValue:1,tension:55,friction:7,useNativeDriver:true})]).start();}
 function feedback():void{Animated.sequence([Animated.spring(scale,{toValue:1.13,useNativeDriver:true}),Animated.spring(scale,{toValue:1,useNativeDriver:true})]).start();}
 function runStagger():void{[stepOne,stepTwo,stepThree].forEach((value)=>value.setValue(0));Animated.stagger(130,[stepOne,stepTwo,stepThree].map((value)=>Animated.timing(value,{toValue:1,duration:350,useNativeDriver:true}))).start();}
 function addItem():void{LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);setItems((v)=>[`Nuevo servicio ${v.length+1}`,...v]);}
 function removeItem():void{if(items.length<1)return;LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);setItems((v)=>v.slice(1));}
 function slideDecay():void{decay.setValue(0);Animated.decay(decay,{velocity:0.8,deceleration:0.94,useNativeDriver:true}).start(({finished})=>{if(finished)decay.setValue(0);});}
 return <SafeAreaView style={styles.safe}><View style={styles.container}><Text style={styles.title}>Laboratorio de animaciones</Text><Text style={styles.detail}>Efectos integrados al flujo de servicios de la cooperativa.</Text>
   <Animated.View style={[styles.hero,{opacity,transform:[{translateY:slide.interpolate({inputRange:[0,1],outputRange:[18,0]})}]}]}><Text style={styles.heroTitle}>Panel de servicios</Text><Text style={styles.detail}>Entrada con timing + spring (parallel)</Text></Animated.View>
   <View style={styles.actions}><Pressable style={styles.button} onPress={entrance}><Text style={styles.buttonText}>Reproducir entrada</Text></Pressable><Pressable style={styles.button} onPress={feedback}><Text style={styles.buttonText}>Feedback spring</Text></Pressable></View>
   <Animated.View style={[styles.progress,{transform:[{scaleX:fade.interpolate({inputRange:[0,1],outputRange:[0.25,1]})}]}]} />
   <View style={styles.actions}><Pressable style={styles.secondary} onPress={runStagger}><Text style={styles.buttonText}>Probar Animated.stagger</Text></Pressable>{[stepOne,stepTwo,stepThree].map((step,index)=><Animated.View key={index} style={[styles.badge,{opacity:step,transform:[{translateY:step.interpolate({inputRange:[0,1],outputRange:[12,0]})}]}]}><Text style={styles.badgeText}>Fase {index+1}</Text></Animated.View>)}</View>
   <Animated.View style={[styles.vehicle,{transform:[{translateX:decay}]}]}><Text style={styles.vehicleText}>🚕 Deslizar con decay</Text></Animated.View><Pressable style={styles.secondary} onPress={slideDecay}><Text style={styles.buttonText}>Ejecutar Animated.decay</Text></Pressable>
   <Text style={styles.section}>Servicios recientes · LayoutAnimation</Text><View style={{transform:[{scale}]}}>{items.map((item,index)=><Animated.View key={`${item}-${index}`} style={styles.row}><Text style={styles.rowText}>{item}</Text></Animated.View>)}</View>
   <View style={styles.actions}><Pressable style={styles.button} onPress={addItem}><Text style={styles.buttonText}>Agregar con LayoutAnimation</Text></Pressable><Pressable style={styles.secondary} onPress={removeItem}><Text style={styles.buttonText}>Quitar</Text></Pressable></View>
 </View></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#0d1117'},container:{padding:18},title:{color:'#fff',fontSize:25,fontWeight:'900'},detail:{color:'#aeb8c4',marginTop:6,lineHeight:20},hero:{backgroundColor:'#10232c',borderRadius:14,padding:18,marginTop:18,borderColor:'#1f6b7a',borderWidth:1},heroTitle:{color:'#fff',fontSize:20,fontWeight:'900'},actions:{flexDirection:'row',gap:8,marginTop:12,flexWrap:'wrap'},button:{backgroundColor:'#238636',padding:11,borderRadius:9},secondary:{backgroundColor:'#30363d',padding:11,borderRadius:9,marginTop:10},buttonText:{color:'#fff',fontWeight:'800',fontSize:12},progress:{height:6,backgroundColor:'#61dafb',borderRadius:9,marginTop:18,alignSelf:'stretch'},vehicle:{backgroundColor:'#161b22',borderRadius:10,padding:12,marginTop:16,alignSelf:'flex-start'},vehicleText:{color:'#fff',fontWeight:'700'},badge:{backgroundColor:'#10232c',padding:9,borderRadius:8},badgeText:{color:'#61dafb',fontWeight:'700',fontSize:11},section:{color:'#fff',fontSize:17,fontWeight:'800',marginTop:22,marginBottom:8},row:{backgroundColor:'#161b22',padding:14,borderRadius:9,marginBottom:7},rowText:{color:'#dce5ee',fontWeight:'600'}});
