import React,{useEffect,useMemo,useState}from'react';import{ActivityIndicator,Alert,FlatList,Pressable,ScrollView,StatusBar,StyleSheet,Switch,Text,TextInput,View}from'react-native';
import{NavigationContainer}from'@react-navigation/native';import{createNativeStackNavigator,NativeStackScreenProps}from'@react-navigation/native-stack';
import{useDrivers,Driver}from'./src/store';
import{QueryClient,QueryClientProvider,useMutation,useQuery,useQueryClient}from'@tanstack/react-query';
import{useForm}from'react-hook-form';import{zodResolver}from'@hookform/resolvers/zod';import{z}from'zod';
import AsyncStorage from'@react-native-async-storage/async-storage';
import{AuthProvider,useAuth}from'./src/auth';
function Drivers(){const drivers=useDrivers(v=>v.drivers),add=useDrivers(v=>v.add);const[name,setName]=useState('');return <View style={s.page}><Text style={s.title}>Conductores</Text><View style={s.row}><TextInput style={[s.input,{flex:1}]} value={name} onChangeText={setName} placeholder="Nombre" placeholderTextColor="#8795a1"/><Pressable style={s.button} onPress={()=>{if(name.trim()){add(name.trim());setName('')}}}><Text style={s.btn}>Agregar</Text></Pressable></View><FlatList data={drivers} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.name}</Text><Text style={s.sub}>{item.unit}</Text></View>}/></View>}
type Routes={Acceso:undefined;Inicio:undefined;Conductores:undefined;Perfil:undefined};const Stack=createNativeStackNavigator<Routes>();
function Home({navigation}:NativeStackScreenProps<Routes,'Inicio'>){const {user}=useAuth();return <View style={s.page}><Text style={s.title}>Hola, {user?.name}</Text><Text style={s.sub}>Semana 8 · autenticación educativa y perfil</Text><Text style={s.sub}>Las cuentas creadas en este ejemplo existen solo en memoria durante esta sesión.</Text><Pressable style={s.button} onPress={()=>navigation.navigate('Conductores')}><Text style={s.btn}>Conductores</Text></Pressable><Pressable style={s.button} onPress={()=>navigation.navigate('Perfil')}><Text style={s.btn}>Mi perfil</Text></Pressable></View>}
function SignIn(){const{login,register}=useAuth(),[creating,setCreating]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState('');async function submit(){setMessage('');if(!email.trim()||password.length<6){setMessage('Ingresa un correo y una contraseña de al menos 6 caracteres.');return}if(creating){if(name.trim().length<2){setMessage('Escribe tu nombre.');return}register(name.trim(),email.trim(),password);return}const ok=login(email.trim(),password);if(!ok)setMessage('No se encontró esa cuenta de demostración. Puedes crear una cuenta en esta app.')}return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>Acceso a la cooperativa</Text><Text style={s.sub}>Autenticación local para practicar. Los campos comienzan vacíos.</Text>{creating&&<TextInput style={s.input} value={name} onChangeText={setName} placeholder="Nombre" placeholderTextColor="#8795a1"/>}<TextInput style={s.input} value={email} onChangeText={setEmail} placeholder="Correo" autoCapitalize="none" keyboardType="email-address" placeholderTextColor="#8795a1"/><TextInput style={s.input} value={password} onChangeText={setPassword} placeholder="Contraseña" secureTextEntry placeholderTextColor="#8795a1"/><Pressable style={s.button} onPress={()=>void submit()}><Text style={s.btn}>{creating?'Crear cuenta':'Ingresar'}</Text></Pressable>{!!message&&<Text style={s.error}>{message}</Text>}<Text onPress={()=>{setCreating(v=>!v);setMessage('')}} style={s.link}>{creating?'Ya tengo una cuenta':'Crear una cuenta de demostración'}</Text></ScrollView>}
function Profile(){const{user,logout}=useAuth();return <View style={s.page}><Text style={s.title}>Mi perfil</Text><View style={s.card}><Text style={s.name}>{user?.name}</Text><Text style={s.sub}>{user?.email}</Text></View><Pressable style={s.button} onPress={logout}><Text style={s.btn}>Cerrar sesión</Text></Pressable></View>}
function SignedIn(){const{user}=useAuth();return <NavigationContainer><Stack.Navigator screenOptions={{headerStyle:{backgroundColor:'#161b22'},headerTintColor:'#fff',contentStyle:{backgroundColor:'#0d1117'}}}>{user?<><Stack.Screen name="Inicio" component={Home}/><Stack.Screen name="Conductores" component={Drivers}/><Stack.Screen name="Perfil" component={Profile}/></>:<Stack.Screen name="Acceso" component={SignIn} options={{headerShown:false}}/>}</Stack.Navigator></NavigationContainer>}
export default function App(){return <AuthProvider><SignedIn/></AuthProvider>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0d1117',padding:18},title:{color:'#fff',fontSize:25,fontWeight:'900'},sub:{color:'#aeb8c4',marginTop:6,marginBottom:8},input:{backgroundColor:'#161b22',borderColor:'#30363d',borderWidth:1,borderRadius:10,padding:12,color:'#fff',marginVertical:5},row:{flexDirection:'row',alignItems:'center',gap:8},button:{backgroundColor:'#238636',borderRadius:9,padding:12,alignItems:'center',marginVertical:7},btn:{color:'#fff',fontWeight:'800'},card:{backgroundColor:'#161b22',borderColor:'#30363d',borderWidth:1,borderRadius:12,padding:14,marginVertical:7},name:{color:'#fff',fontWeight:'800',fontSize:16},error:{color:'#ff8a80',marginVertical:8},link:{color:'#61dafb',textAlign:'center',fontWeight:'700',padding:12},amount:{color:'#8ce99a',fontSize:27,fontWeight:'900',marginTop:15}});