import React,{useEffect,useMemo,useState}from'react';import{ActivityIndicator,Alert,FlatList,Pressable,ScrollView,StatusBar,StyleSheet,Switch,Text,TextInput,View}from'react-native';
import{NavigationContainer}from'@react-navigation/native';import{createNativeStackNavigator,NativeStackScreenProps}from'@react-navigation/native-stack';
import{useDrivers,Driver}from'./src/store';
import{QueryClient,QueryClientProvider,useMutation,useQuery,useQueryClient}from'@tanstack/react-query';
import{useForm}from'react-hook-form';import{zodResolver}from'@hookform/resolvers/zod';import{z}from'zod';
import AsyncStorage from'@react-native-async-storage/async-storage';
function Drivers(){const drivers=useDrivers(v=>v.drivers),add=useDrivers(v=>v.add);const[name,setName]=useState('');return <View style={s.page}><Text style={s.title}>Conductores</Text><View style={s.row}><TextInput style={[s.input,{flex:1}]} value={name} onChangeText={setName} placeholder="Nombre" placeholderTextColor="#8795a1"/><Pressable style={s.button} onPress={()=>{if(name.trim()){add(name.trim());setName('')}}}><Text style={s.btn}>Agregar</Text></Pressable></View><FlatList data={drivers} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.name}</Text><Text style={s.sub}>{item.unit}</Text></View>}/></View>}
type Routes={Inicio:undefined;Conductores:undefined;Preferencias:undefined};const Stack=createNativeStackNavigator<Routes>();const KEY='taxi-drivers-week07';
function Home({navigation}:NativeStackScreenProps<Routes,'Inicio'>){return <View style={s.page}><Text style={s.title}>Cooperativa de Taxis</Text><Text style={s.sub}>Semana 7 · almacenamiento local</Text><Text style={s.sub}>Conductores y preferencias persisten en el dispositivo.</Text><Pressable style={s.button} onPress={()=>navigation.navigate('Conductores')}><Text style={s.btn}>Conductores</Text></Pressable><Pressable style={s.button} onPress={()=>navigation.navigate('Preferencias')}><Text style={s.btn}>Preferencias</Text></Pressable></View>}
function Drivers(){const drivers=useDrivers(v=>v.drivers),add=useDrivers(v=>v.add);const[name,setName]=useState('');return <View style={s.page}><Text style={s.title}>Conductores guardados</Text><View style={s.row}><TextInput style={[s.input,{flex:1}]} value={name} onChangeText={setName} placeholder="Nombre" placeholderTextColor="#8795a1"/><Pressable style={s.button} onPress={()=>{if(name.trim()){add(name.trim());setName('')}}}><Text style={s.btn}>Agregar</Text></Pressable></View><FlatList data={drivers} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.name}</Text></View>}/></View>}
function Preferences(){const[compact,setCompact]=useState(false),[ready,setReady]=useState(false);useEffect(()=>{void AsyncStorage.getItem('taxi-compact-week07').then(v=>setCompact(v==='true')).finally(()=>setReady(true))},[]);async function change(value:boolean){setCompact(value);await AsyncStorage.setItem('taxi-compact-week07',String(value))}return <View style={s.page}><Text style={s.title}>Preferencias</Text><View style={s.row}><Text style={s.name}>Vista compacta</Text><Switch value={compact} onValueChange={v=>void change(v)}/></View><Text style={s.sub}>{ready?'La preferencia se recuperó del almacenamiento local.':'Cargando preferencia…'}</Text></View>}
function Main(){return <NavigationContainer><Stack.Navigator screenOptions={{headerStyle:{backgroundColor:'#161b22'},headerTintColor:'#fff',contentStyle:{backgroundColor:'#0d1117'}}}><Stack.Screen name="Inicio" component={Home}/><Stack.Screen name="Conductores" component={Drivers}/><Stack.Screen name="Preferencias" component={Preferences}/></Stack.Navigator></NavigationContainer>}
export default function App(){return <Main/>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0d1117',padding:18},title:{color:'#fff',fontSize:25,fontWeight:'900'},sub:{color:'#aeb8c4',marginTop:6,marginBottom:8},input:{backgroundColor:'#161b22',borderColor:'#30363d',borderWidth:1,borderRadius:10,padding:12,color:'#fff',marginVertical:5},row:{flexDirection:'row',alignItems:'center',gap:8},button:{backgroundColor:'#238636',borderRadius:9,padding:12,alignItems:'center',marginVertical:7},btn:{color:'#fff',fontWeight:'800'},card:{backgroundColor:'#161b22',borderColor:'#30363d',borderWidth:1,borderRadius:12,padding:14,marginVertical:7},name:{color:'#fff',fontWeight:'800',fontSize:16},error:{color:'#ff8a80',marginVertical:8},link:{color:'#61dafb',textAlign:'center',fontWeight:'700',padding:12},amount:{color:'#8ce99a',fontSize:27,fontWeight:'900',marginTop:15}});