import React,{useEffect,useMemo,useState}from'react';import{ActivityIndicator,Alert,FlatList,Pressable,ScrollView,StatusBar,StyleSheet,Switch,Text,TextInput,View}from'react-native';
import{NavigationContainer}from'@react-navigation/native';import{createNativeStackNavigator,NativeStackScreenProps}from'@react-navigation/native-stack';
import{useDrivers,Driver}from'./src/store';
import{QueryClient,QueryClientProvider,useMutation,useQuery,useQueryClient}from'@tanstack/react-query';
import{useForm}from'react-hook-form';import{zodResolver}from'@hookform/resolvers/zod';import{z}from'zod';
function Drivers(){const drivers=useDrivers(v=>v.drivers),add=useDrivers(v=>v.add);const[name,setName]=useState('');return <View style={s.page}><Text style={s.title}>Conductores</Text><View style={s.row}><TextInput style={[s.input,{flex:1}]} value={name} onChangeText={setName} placeholder="Nombre" placeholderTextColor="#8795a1"/><Pressable style={s.button} onPress={()=>{if(name.trim()){add(name.trim());setName('')}}}><Text style={s.btn}>Agregar</Text></Pressable></View><FlatList data={drivers} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.name}</Text><Text style={s.sub}>{item.unit}</Text></View>}/></View>}
type Routes={Inicio:undefined;Conductores:undefined;Viajes:undefined};const Stack=createNativeStackNavigator<Routes>();type Driver={id:string;name:string;unit:string};let rows:Driver[]=[{id:'d1',name:'Carlos Mendoza',unit:'Móvil 01'},{id:'d2',name:'Ana Rodríguez',unit:'Móvil 02'}];const schema=z.object({name:z.string().trim().min(2,'Escribe al menos 2 caracteres.'),phone:z.string().trim().regex(/^[0-9+() -]{7,18}$/,'Escribe un teléfono válido.')});type FormValues=z.infer<typeof schema>;
function Home({navigation}:NativeStackScreenProps<Routes,'Inicio'>){return <View style={s.page}><Text style={s.title}>Cooperativa de Taxis</Text><Text style={s.sub}>Semana 6 · formularios y validación</Text><Text style={s.sub}>Abre Conductores para probar el formulario con mensajes de validación.</Text><Pressable style={s.button} onPress={()=>navigation.navigate('Conductores')}><Text style={s.btn}>Conductores</Text></Pressable><Pressable style={s.button} onPress={()=>navigation.navigate('Viajes')}><Text style={s.btn}>Viajes</Text></Pressable></View>}
function Drivers(){const drivers=useDrivers(v=>v.drivers),add=useDrivers(v=>v.add);const[name,setName]=useState(''),[phone,setPhone]=useState(''),[error,setError]=useState('');function save(){const result=schema.safeParse({name,phone});if(!result.success){setError(result.error.issues[0]?.message??'Revisa los campos.');return}add(result.data.name);setName('');setPhone('');setError('')}return <View style={s.page}><Text style={s.title}>Nuevo conductor</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Nombre completo" placeholderTextColor="#8795a1"/><TextInput style={s.input} value={phone} onChangeText={setPhone} placeholder="Teléfono" keyboardType="phone-pad" placeholderTextColor="#8795a1"/><Pressable style={s.button} onPress={save}><Text style={s.btn}>Validar y guardar</Text></Pressable>{!!error&&<Text style={s.error}>{error}</Text>}<FlatList style={{marginTop:12}} data={drivers} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.name}</Text><Text style={s.sub}>{item.unit}</Text></View>}/></View>}
function Trips(){const form=useForm<{origin:string;destination:string;fare:string}>({resolver:zodResolver(z.object({origin:z.string().min(2,'Indica el origen.'),destination:z.string().min(2,'Indica el destino.'),fare:z.string().regex(/^\d+$/,'Tarifa numérica requerida.')})),defaultValues:{origin:'',destination:'',fare:''}});return <View style={s.page}><Text style={s.title}>Formulario de viaje</Text>{(['origin','destination','fare'] as const).map(k=><View key={k}><TextInput style={s.input} value={form.watch(k)} onChangeText={v=>form.setValue(k,v,{shouldValidate:true})} placeholder={k==='origin'?'Origen':k==='destination'?'Destino':'Tarifa COP'} placeholderTextColor="#8795a1" keyboardType={k==='fare'?'numeric':'default'}/>{!!form.formState.errors[k]&&<Text style={s.error}>{form.formState.errors[k]?.message}</Text>}</View>)}<Pressable style={s.button} onPress={form.handleSubmit(()=>Alert.alert('Correcto','Datos válidos para registrar un viaje.'))}><Text style={s.btn}>Validar datos</Text></Pressable></View>}
function Main(){return <NavigationContainer><Stack.Navigator screenOptions={{headerStyle:{backgroundColor:'#161b22'},headerTintColor:'#fff',contentStyle:{backgroundColor:'#0d1117'}}}><Stack.Screen name="Inicio" component={Home}/><Stack.Screen name="Conductores" component={Drivers}/><Stack.Screen name="Viajes" component={Trips}/></Stack.Navigator></NavigationContainer>}
export default function App(){return <Main/>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0d1117',padding:18},title:{color:'#fff',fontSize:25,fontWeight:'900'},sub:{color:'#aeb8c4',marginTop:6,marginBottom:8},input:{backgroundColor:'#161b22',borderColor:'#30363d',borderWidth:1,borderRadius:10,padding:12,color:'#fff',marginVertical:5},row:{flexDirection:'row',alignItems:'center',gap:8},button:{backgroundColor:'#238636',borderRadius:9,padding:12,alignItems:'center',marginVertical:7},btn:{color:'#fff',fontWeight:'800'},card:{backgroundColor:'#161b22',borderColor:'#30363d',borderWidth:1,borderRadius:12,padding:14,marginVertical:7},name:{color:'#fff',fontWeight:'800',fontSize:16},error:{color:'#ff8a80',marginVertical:8},link:{color:'#61dafb',textAlign:'center',fontWeight:'700',padding:12},amount:{color:'#8ce99a',fontSize:27,fontWeight:'900',marginTop:15}});